title: Brainy Control
description: A web repository literature review amalgamation
theme: just-the-docs

url: https://ingaschoeyen.github.io/BrainyControl2/

aux_links:
  Repository: https://github.com/ingaschoeyen/BrainyControl2
