title: Brainy Control
description: A web repository literature review amalgamation
theme: just-the-docs

url: https://ingaschoeyen.github.io/BrainyControl2/

aux_links:
  Repository: https://github.com/ingaschoeyen/BrainyControl2

back_to_top: true
back_to_top_text: "Back to top"

logo: "/docs/assets/images/slack_logo2B.png"
favicon_ico: "/docs/assets/images/slack_logo2B.ico"
