title: Brainy Control
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://ingaschoeyen.github.io/BrainyControl2/

aux_links:
  Literature: literature.html
